### ISSUE TITLE
Unable to install the extension with composer

### ISSUE THREAD

**Issue by Patric96** [hofff/contao-social-tags#1]
If i try to install the extension with `composer require hofff/contao-social-tags` it throws the following error:
 _[InvalidArgumentException]                                                    
  Could not find a version of package hofff/contao-social-tags matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability._

Any known Issues about this case?

**Comment by frontendschlampe** [comment]
You have to require version `dev-master`, because we don't have a stable version yet. But the dev-version is nearly ready and we use it already in some installations.

**Comment by Patric96** [comment]
Perfect, that's it!
