### ISSUE TITLE
Fallback Infos für og:image u.a. prüfen

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-social-tags#10]
Wenn bei Events, News oder FAQ "Social Tags definieren" nicht aktiviert ist, dann wird auch kein Bild beim Teilen ausgegeben. Erst wenn beim Beitrag die Social Tags definiert sind, wird ein Bild geteilt.

Wenn die Social Tags nicht definiert sind, sollte es jedoch so sein, dass das Bild vom Beitrag selbst als og:image gesetzt wird (ggf. müsste man das nochmal mit jemandem diskutieren, der sich damit auskennt – wg. Bildgrößen). Wenn es kein Beitragsbild gibt und auch keine Social Tags definiert sind, dann sollte das Fallbackbild aus der Seitenstruktur genommen werden, was irgendwo hinterlegt ist.

**Comment by fritzmg** [comment]
This would be fixed by #14 I think.

**Comment by berecont** [comment]
does that mean if I use fritzmg/contao-social-tags instead hofff/contao-social-tags everything is fine?

**Comment by frontendschlampe** [comment]
fritzmg/contao-social-tags is just a fork of hofff/contao-social-tags to provide the pull requests. You can install the dev-version for the moment, but we will merge it in hofff/contao-social-tags asap.

**Comment by dmolineus** [comment]
Fallback für Bilder als auch Twitter Site und Twitter Creator wurde implementiert.
