### ISSUE TITLE
og:description abfragen & weitergeben

### ISSUE THREAD

**Issue by operatorone** [hofff/contao-social-tags#11]
Hi Nicky,

hättest du eine Idee, wie ich den Inhalt von og:description aus einem Nachrichtenbeitrag

`<meta prefix="og: http://ogp.me/ns#" property="og:description" content="...">`

an die Meta-Beschreibung weitergeben kann?

` <meta name="description" content="...">`

Viele Grüße
Til

**Comment by fritzmg** [comment]
Why do you want it this way? The default is the other way around.

**Comment by operatorone** [comment]
Because in C 4.4 I have no meta tags in the news and the teaser is the meta description. With an update to 4.9 it'll be settled.
