### ISSUE TITLE
Fehler in Contao 4.9

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-social-tags#2]
Beim Aufruf der Seitenstruktur kommt folgender Fehler:

`None of the chained routers were able to generate route: Route 'hofff_contao_social_tags_facebook_lint' not found`

**Comment by dmolineus** [comment]
Leere mal den Cache, sowohl `dev` als auch `prod`.

Related:

 - https://github.com/contao/contao/issues/1435
 - https://github.com/contao/contao/pull/1369
 - https://github.com/contao/contao/issues/1361

**Comment by frontendschlampe** [comment]
määääh ... geht
