### ISSUE TITLE
Composer-Meldung sobald diese Erweiterung installiert ist

### ISSUE THREAD

**Issue by srhinow** [hofff/contao-social-tags#22]
Contao 4.4.55
PHP 7.4

Sobald diese Erweiterung erfolgreich mit allen DB-Updates installiert ist wird auf Seiten wo Formulare (keine Ahnung ob es in dem Zusammenhang ist) eine weiße Seite mit der Fehlermeldung:
'Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0"'
angezeigt obwohl PHP 7.4 eingerichtet ist. Wird so auch vom Contao-Manager erkannt und bei der Installation wird auch kein Fehler angezeigt.

**Comment by dmolineus** [comment]
> 'Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0"'

Erscheint die Meldung wirklich im Frontend auf der Formularseite? Wo kann man das nachvollziehen? Was gibt der DEV-Modus aus?

**Comment by dmolineus** [comment]
Ich kann das Problem mit meinen Installation nicht nachvollziehen und setze die Extension in diversen Projekten ein. Bitte einen passenden Stacktrace zur Verfügung stellen.
