### ISSUE TITLE
onGetContentElement() must be of the type string

### ISSUE THREAD

**Issue by Samson1964** [hofff/contao-social-tags#23]
Ich habe gerade die Erweiterung in Contao 4.9 installiert. Funktioniert soweit. Allerdings wirft die Erweiterung einen Fehler aus, wenn ich per XMLHttpRequest auf Events zugreife:

Argument 2 passed to Hofff\Contao\SocialTags\EventListener\Hook\NewsReaderListener::onGetContentElement() must be of the type string, null given, called in /vendor/contao/core-bundle/src/Resources/contao/library/Contao/Controller.php on line 582
Exception, TypeError in vendor/hofff/contao-social-tags/src/EventListener/Hook/NewsReaderListener.php (line 45)

**Comment by dmolineus** [comment]
Der Fehler wird durch eine andere Extension erzeugt, die sich nicht an die Type-Deklarationen von Contao halten. Ein Inhaltselement muss immer ein `string` zuurückgeben. Das ist bei einer Extension nicht der Fall.

**Comment by MrFastDie** [comment]
I guess I'm gonna fork this project than - as I can see this also happens for others in issues.
