### ISSUE TITLE
og:type wird nicht ausgegeben

### ISSUE THREAD

**Issue by frontendschlampe** [hofff/contao-social-tags#3]
Obwohl og:type bei der Seite gesetzt ist, wird es im Quellcode nicht ausgegeben.

**Comment by dmolineus** [comment]
Fix released as version 1.0.2.

**Comment by christianbarkowsky** [comment]
Der og:type Tag wird leider noch nicht gesetzt.

**Comment by dmolineus** [comment]
Wie lässt sich das reproduzieren? Welche Einstellungen sind vorgenommen? Aus welcher Datenquelle sollte der oh:title gezogen werden?

**Comment by christianbarkowsky** [comment]
Fehler tritt noch bei den News auf.

Bitte noch den Link zum FB Validator fixen: https://developers.facebook.com/tools/debug/

**Comment by dmolineus** [comment]
Fehler ist nun auch für News, Events and FAQs behoben. Debug Link ist aktualisiert. Released als 1.0.3.
