### ISSUE TITLE
Uncaught PHP Exception TypeError

### ISSUE THREAD

**Issue by herrrilke** [hofff/contao-social-tags#4]
hallo,
in einer frischen C 4.9.5 kommt mit contao-social-tags 1.03 der fehler:

`request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 2 passed to Hofff\Contao\SocialTags\EventListener\Hook\FaqReaderListener::onGetFrontendModule() must be of the type string, null given, called in C:\wamp64\www\vendor\contao\core-bundle\src\Resources\contao\library\Contao\Controller.php on line 431" at C:\wamp64\www\vendor\hofff\contao-social-tags\src\EventListener\Hook\FaqReaderListener.php line 55 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 2 passed to Hofff\\Contao\\SocialTags\\EventListener\\Hook\\FaqReaderListener::onGetFrontendModule() must be of the type string, null given, called in C:\\wamp64\\www\\vendor\\contao\\core-bundle\\src\\Resources\\contao\\library\\Contao\\Controller.php on line 431 at C:\\wamp64\\www\\vendor\\hofff\\contao-social-tags\\src\\EventListener\\Hook\\FaqReaderListener.php:55)"} []`

gibt's da was zu verändern auf meiner seite?

VG
karsten

**Comment by dmolineus** [comment]
Anscheinend generiert ein Frontendmodul oder ein Hook-Listener des `getFrontendModul` keine Ausgabe, sondern gibt `NULL` zurück. Mir ist ein entsprechendes Verhalten in Contao nicht bekannt, daher wird dies vermutlich durch eine Dritterweiterung verursacht.

**Comment by herrrilke** [comment]
hallo,
vielen dank für den hinweis!
da war ich auf der falschen fährte. es war ein von mir falsch konfiguriertes "magmell-agentur/contao-boxes" modul.
jetzt funktioniert alles 

danke dir nochmal!
